### ISSUE TITLE
Unable to install using Ansible playbook - GeoIP fails

### ISSUE THREAD

**Issue by ridgebackdad** [3ilson/ansible-pfelk#1]
The directions are a bit unclear as to the fact that the Ansible install will fail at the 
install maxmind

    download GeoIP databases
    setup a cron job for automated updates

steps.

Assuming that I need to let it fail, then get on the target host and edit the /etc/GeoIP.conf file?

once I do that and re-run the Ansible playbook, I then get this:

fatal: [pfelk.yourcompany.org]: FAILED! => {
    "changed": true,
    "cmd": "geoipupdate -d /usr/share/GeoIP/",
    "delta": "0:00:00.006563",
    "end": "2020-02-25 02:02:09.074367",
    "invocation": {
        "module_args": {
            "_raw_params": "geoipupdate -d /usr/share/GeoIP/",
            "_uses_shell": true,
            "argv": null,
            "chdir": null,
            "creates": null,
            "executable": null,
            "removes": null,
            "stdin": null,
            "stdin_add_newline": true,
            "strip_empty_ends": true,
            "warn": true
        }
    },
    "msg": "non-zero return code",
    "rc": 1,
    "start": "2020-02-25 02:02:09.067804",
    "stderr": "error loading configuration file: `EditionIDs' is in the config multiple times",
    "stderr_lines": [
        "error loading configuration file: `EditionIDs' is in the config multiple times"
    ],
    "stdout": "",
    "stdout_lines": []
}

**Comment by fktkrt** [comment]
Hi, thank you for opening an issue!

I have transferred this issue on the corresponding repository, since we are in the progress of breaking down this product into more repos.

First, I would like to ask whether you used the files in the main repo, or the new ones here, in the destination repo? Those original files are no longer maintained, and will be removed soon.

This new repo has a more detailed bug/issue reporting template asking for more information like 
 - OS (`printf "$(uname -srm)\n$(cat /etc/os-release)\n"`):
 - Version of Ansible (`ansible --version`):
 - Version of Python (`python --version`):

since these can help with troubleshooting certain bugs.

So, could give it one more try with the files provided in this repo, and report back with the results and the aforementioned package versions?

FYI, we have incorporated automated CI pipelines to test all our commits pushed into these repos, you can check the result of this ones here: https://travis-ci.org/3ilson/ansible-pfelk

You can see that this workflow uses the latest ansible and the latest python version and can add the referenced line into the config file, see this excerpt for further details:

```
changed: [127.0.0.1] => {
    "backup": "",
    "changed": true,
    "diff": {
        "after": "",
        "after_header": "/etc/GeoIP.conf (content)",
        "before": "",
        "before_header": "/etc/GeoIP.conf (content)"
    },
    "invocation": {
        "module_args": {
            "attributes": null,
            "backrefs": false,
            "backup": false,
            "content": null,
            "create": true,
            "delimiter": null,
            "directory_mode": null,
            "firstmatch": false,
            "follow": false,
            "force": null,
            "group": null,
            "insertafter": null,
            "insertbefore": null,
            "line": "EditionIDs GeoLite2-City GeoLite2-Country GeoLite2-ASN",
            "mode": null,
            "owner": null,
            "path": "/etc/GeoIP.conf",
            "regexp": null,
            "remote_src": null,
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "src": null,
            "state": "present",
            "unsafe_writes": null,
            "validate": null
        }
    },
    "msg": "line added"
}
``` 

Looking forward to your feedback!

**Comment by skluthe** [comment]
Solution is to comment out the first section of editions because it's defined twice in the config.

**Comment by fktkrt** [comment]
> Solution is to comment out the first section of editions because it's defined twice in the config.

Made some changes generating the `.conf` file to address this issue.
Please let me know if the problem persists!
