### ISSUE TITLE
Travis-CI Failes After Updates (configuration files/main.yml)

### ISSUE THREAD

**Issue by a3ilson** [3ilson/ansible-pfelk#9]
**Describe the bug**
Travis-CI Failing.  Updated the configuration files and amended the logstash>>main.yml file with updated paths. However, Travis-CI continues to fail.  Made updates to main.yml...reverted to previously working version but still received Travis-CI failures.  Will peel back and continue to troubleshoot later next week as time permits. 

**To Reproduce**
Resort to previously working main.yml and/or amend with updates...Travis-CI fails

**Comment by fktkrt** [comment]
Hey,

I've started to troubleshoot this multiple times already.
Unfortunately, it looks like a systemd issue in the end (please see https://github.com/ansible/ansible/issues/48786 for details for example).

During my investigations, I refactored the java role, switched to focal distro (it introduced multiple new issues), but this brought some suboptimal configurations to my attention. These are fixed (although w/ logstash I had to include a workaround).

The steps mentioned above solved/masked the kibana error you've reported, but it came out again, but this time for logstash.
The generic advice for this, is to manually `systemctl daemon-reload` systemd, but it doesn't seem to have any effect.
After all, it shouldn't be neccesery, since `daemon_reload: yes` would address this exact issue.

I keep trying, as time permits.

**Comment by a3ilson** [comment]
Fixed
